### PR TITLE
[FEAT] Implement Internationalisation

### PR DESCRIPTION
**Pull request by lokesh-veerappan**
## Description

[x] Implement Internationalisation for all the text
[ ] Make it reusable so that it can be integrated with data coming from servers as well
[x] Maintain guidelines

## Related Issues
#31 

## Changes Made

Internationalisation implemented using the i18next library.

## Checklist

- [x] I have read and followed the [Contribution Guidelines](https://github.com/DevSoc-Asansol2023/DevSoc-Main/blob/main/Contributing.md).
- [x] All new and existing tests passed.
- [ ] I have updated the documentation to reflect the changes I've made.
- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have shared relevant screenshots or videos for both desktop and mobile view.

## Screenshots/video/urls
Screenshot_23
Screenshot_24

## Note to reviewers
There is no dynamic content yet based on data fetched from APIs, the i18next library can integrate dynamic content as well by injecting variables when needed in the future.

### CODE REVIEW

**Comment by lokjaw** [comment]
@ArnabChatterjee20k This resolves #31

**Comment by ArnabChatterjee20k** [comment]
Can you share some screenshots to see the working pages

**Comment by lokjaw** [comment]
> Can you share some screenshots to see the working pages

There is only one page and I have shared the screenshots above. Do you need more specific screenshots?

**Comment by ArnabChatterjee20k** [comment]
Can you add some languages like hindi and bengali. Only adding English is not serving the purpose. You can add one language toggler if you want.
Since we are targeting community from various genres so I think adding multiple language is what we need

**Comment by lokjaw** [comment]
@ArnabChatterjee20k I only speak English. I hope you're not expecting me to translate everything. 
But I can setup configurations and toggler for multiple languages and then someone can wok on translations specifically under each translation files for respective languages.
Let me know if that's satisfactory.

**Comment by ArnabChatterjee20k** [comment]
> @ArnabChatterjee20k I only speak English. I hope you're not expecting me to translate everything. But I can setup configurations and toggler for multiple languages and then someone can wok on translations specifically under translation files for respective languages. Let me know if that's satisfactory.

Adding a toggler will be great point setup for this project
Thanks @lokjaw

**Pull request closed without merging**
