### PR TITLE
Removing overflow of the website

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
Website was overflowing the x direction which was solve by adding `overflow-x-hidden` class in cards.jsx file

### CODE REVIEW

**Comment by ArnabChatterjee20k** [comment]
Thank you @DhairyaMajmudar
Can you please share a screenshot in both desktop and mobile view

**Comment by DhairyaMajmudar** [comment]
> Thank you @DhairyaMajmudar Can you please share a screenshot in both desktop and mobile view

Sure Sir 👍

**Comment by ArnabChatterjee20k** [comment]
> > Thank you @DhairyaMajmudar Can you please share a screenshot in both desktop and mobile view
> 
> Sure Sir 👍

Don't call me sir
I am just a contributor like you 😅

**Comment by DhairyaMajmudar** [comment]
**Desktop**
Screenshot 2023-10-09 at 12-42-57 Dev Soc


**Responsive**
Screenshot 2023-10-09 at 12-47-49 Dev Soc

**Comment by ArnabChatterjee20k** [comment]
Its looking nice
@DhairyaMajmudar is getting some merge conflicts 
can you resolve that

**Comment by DhairyaMajmudar** [comment]
> Its looking nice @DhairyaMajmudar is getting some merge conflicts can you resolve that

It might be because some other contributors also has contributed after mine

**Comment by DhairyaMajmudar** [comment]
I can resolve it but Have to send pr again

**Comment by DhairyaMajmudar** [comment]
yeah done it the editor only 😄 Thanks to top of the world github website 😊

**Comment by ArnabChatterjee20k** [comment]
> I can resolve it but Have to send pr again

If you have already made a pr, then you dont have to make another one. Just push the changes in the same branch. The pr will automatically get updated.
PR is nothing but making a request to merge a branch.

**Comment by ArnabChatterjee20k** [comment]
> yeah done it the editor only 😄 Thanks to top of the world github website 😊

Cool

**Review by ArnabChatterjee20k — APPROVED** [review]

**Comment by DhairyaMajmudar** [comment]
Thank you @ArnabChatterjee20k bhaiya for merging my PR 🙏

**Pull request merged**
