### PR TITLE
Fixing issue #6 : [Feature] Adding an automation of issuing a pr template

### PR DESCRIPTION
**Pull request by Akib-Vijapura**
Successfully add template for Pull Request automatic templet.

Fixes : #6

### CODE REVIEW

**Review by ArnabChatterjee20k — COMMENTED** [review]
Add one more checkpoint to add both desktop and mobile view videos or screenshots

**Comment by ArnabChatterjee20k** [comment]
@Akib-Vijapura any updates?

**Comment by Akib-Vijapura** [comment]
Hey @ArnabChatterjee20k, I've already submitted a pull request for that. Kindly take a look.

**Comment by ArnabChatterjee20k** [comment]
@Akib-Vijapura I am talking about the requested changes. The package.lock file is showing changes which is not supposed to be changed

**Comment by Akib-Vijapura** [comment]
Ohh right!, Sorry for that I'll fix it out

**Review by ArnabChatterjee20k — APPROVED** [review]
Thanks for making the required changes

**Comment by ArnabChatterjee20k** [comment]
Thanks @Akib-Vijapura for your contribution
I am merging it

**Pull request merged**
