### PR TITLE
Update navbar.jsx

### LINKED ISSUE #2: [Feature] Improve the navbar
Improve the navbar by fixing its style and make it responsive in all devices

### PR DESCRIPTION
**Pull request by Ritish134**
Added popup menu for smaller screens to display navbar elements. closes #2

### CODE REVIEW

**Comment by ArnabChatterjee20k** [comment]
@Ritish134 please provide some screenshots

**Comment by Ritish134** [comment]
Sure here it is: 
popup_menu
pop2

**Comment by ArnabChatterjee20k** [comment]
Can you please give some background to the links like this [Headless ui](https://headlessui.com/react/menu)
You can use the headless ui menu to make this more effective

**Comment by Ritish134** [comment]
Ok , will do it.

**Comment by Ritish134** [comment]
How is it now : 
navbar
nav2

**Comment by ArnabChatterjee20k** [comment]
@Ritish134 yes its looking nice
I am merging it

> How is it now : navbar nav2

Provide some margin to the menu of right side as well so that the the left of the hamburger and the menu comes in same vertical line.

**Comment by Ritish134** [comment]
like this : 
navfinal

**Comment by ArnabChatterjee20k** [comment]
Thank you @Ritish134 for making the adjustments
I am merging it

**Pull request merged**
