### PR TITLE
fixed the responsiveness in smaller devices

### LINKED ISSUE #5: [Bug] FIx the ui and responsiveness of the call to action section
image
image

Make it according to our design file https://www.figma.com/file/C1xLyZe2wvYVFdusEHRVGZ/DevSoc?type=design&node-id=0-1&mode=design&t=TAnWT775AtPhgUuM-0

These components are having responsiveness issues in smaller devices.

### PR DESCRIPTION
**Pull request by vedika-gupta**
## What does this PR do?

This PR fixes the responsiveness of elements for smaller devices as mentioned in the issue.

Fixes #5

Screenshot 2023-10-07 212915

Screenshot 2023-10-07 213010

## Type of change

 - Bug fix (fixed alignment and responsiveness of elements)

### CODE REVIEW

**Comment by ArnabChatterjee20k** [comment]
Thanks @vedika-gupta its actually looking nice
@vedika-gupta it is getting some merge conflicts can you resolve that

**Comment by vedika-gupta** [comment]
Resolved the merge conflicts.

**Comment by vedika-gupta** [comment]
@ArnabChatterjee20k Pull request is now ready for review and merging.

Screenshot 2023-10-10 234953

**Comment by ArnabChatterjee20k** [comment]
Thanks @vedika-gupta for your contribution
I am merging it

**Pull request merged**
