### PR TITLE
Profile Created

### PR DESCRIPTION
**Pull request by jgyfutub**
I have created the Profile web page. Although I have not put star background because I was not able to download it from figma.I request to please review my pr.Solves issue #12

Dev Soc and 6 more pages - Personal - Microsoft​ Edge 07-10-2023 21_15_19

### CODE REVIEW

**Comment by jgyfutub** [comment]
@ArnabChatterjee20k please review it. I have added meow image as a sample for cover and profile

**Comment by ArnabChatterjee20k** [comment]
Please make the header profile section according to the design file
Please move the avatar portion to the left side instead of middle like the way present in the figma file
Here is the star background

bg-stars-1 webp

Also make tabs interactable

**Comment by jgyfutub** [comment]
Dev Soc and 5 more pages - Personal - Microsoft​ Edge 07-10-2023 23_58_27
See if this works fine.

**Comment by ArnabChatterjee20k** [comment]
One question are the tabs working?
The issue is this "Implement the user profile system to track the user's participation in various events using horizontal cards(use dummy data)"
So please try to implement some cards as well to test the tab switching is working or not

You can use react router and outlet component of react router to do this
If any confusion or any help needed msg here

**Comment by ArnabChatterjee20k** [comment]
Also please try to capture a video as these are more of kind of interactivity problem statements

**Comment by jgyfutub** [comment]
> One question are the tabs working?
> The issue is this "Implement the user profile system to track the user's participation in various events using horizontal cards(use dummy data)"
> So please try to implement some cards as well to test the tab switching is working or not
> 
> You can use react router and outlet component of react router to do this
> If any confusion or any help needed msg here

No the tabs working hasn't been implemented yet.

**Comment by ArnabChatterjee20k** [comment]
> > One question are the tabs working?
> > The issue is this "Implement the user profile system to track the user's participation in various events using horizontal cards(use dummy data)"
> > So please try to implement some cards as well to test the tab switching is working or not
> > You can use react router and outlet component of react router to do this
> > If any confusion or any help needed msg here
> 
> No the tabs working hasn't been implemented yet.

Please implement the tabs working cause that is important

**Comment by jgyfutub** [comment]
Yes I will implement it👍👍

**Comment by jgyfutub** [comment]
https://github.com/DevSoc-Asansol2023/DevSoc-Main/assets/97391064/41485c8d-01b0-4b6a-8fdf-06a958187f66

I have implemented functionality of tabs with two horizontal cards. Please review it @ArnabChatterjee20k

**Comment by ArnabChatterjee20k** [comment]
Thanks @jgyfutub for your valuable contribution.
One more question, this is responsive nah?

**Comment by jgyfutub** [comment]
There is some problem in mobile version.The cover photo is getting too small but although I tried to implement 
`sm` class of tailwind css it was not implementing.And the background image is not fixed in background while scrolling even though I  `backgroundAttachement: 'fixed' ` it was not applying.

**Comment by ArnabChatterjee20k** [comment]
Ah without responsiveness we can't accept this pr cause for that we need to create one issue.
Try to fix it. If any help required post here

**Comment by jgyfutub** [comment]
> Ah without responsiveness we can't accept this pr cause for that we need to create one issue.
> Try to fix it. If any help required post here

I wrote the code for responsiveness as you can see in my last comment but the changes were not coming. What shall I do?

**Comment by jgyfutub** [comment]
Background Attachment - Tailwind CSS and 6 more pages - Personal - Microsoft​ Edge 08-10-2023 16_01_32

I have fixed all the responsive problems.Please review this @ArnabChatterjee20k

**Comment by ArnabChatterjee20k** [comment]
Yeah its nice
But make some improvement
In mobile
* Make the width of the profile banner image full width
* Reduce the size of profile image
* Bring the names and text below profile image
* Make the width of the tab section to full width so that tabs move a bit left in mobile. Reduce the size of tab text

**Comment by jgyfutub** [comment]
Dev Soc and 3 more pages - Personal - Microsoft​ Edge 08-10-2023 21_22_24

I have improved as instructed. Please review it @ArnabChatterjee20k

**Comment by ArnabChatterjee20k** [comment]
The ui is looking nice
but please make requested changes

**Comment by jgyfutub** [comment]
> The ui is looking nice
> but please make requested changes

I have done as you said reducing the profile size ,bringing the name below ,cover photo to full and size of tabs increased

**Comment by ArnabChatterjee20k** [comment]
> > The ui is looking nice
> > but please make requested changes
> 
> I have done as you said reducing the profile size ,bringing the name below ,cover photo to full and size of tabs increased

Yes you have done that but you have done some mistake in controlling the logic of the tabs handling. You made that logic for only two tabs. What if we have more than 2 tabs. You can see where I requested the changes in the files changed tab

**Comment by jgyfutub** [comment]
> > > The ui is looking nice
> > > but please make requested changes
> > 
> > I have done as you said reducing the profile size ,bringing the name below ,cover photo to full and size of tabs increased
> 
> Yes you have done that but you have done some mistake in controlling the logic of the tabs handling. You made that logic for only two tabs. What if we have more than 2 tabs. You can see where I requested the changes in the files changed tab

So I just have to change the tab handling functionality.Is every other thing fine?

**Comment by ArnabChatterjee20k** [comment]
I am reviewing the code step by step.
First I checked the ui and responsiveness
Now I am checking the code quality.
For now yes the tabs thing

**Comment by jgyfutub** [comment]
I have changed the logic for tab handling such that it can handle multiple tabs.Please review it @ArnabChatterjee20k

**Comment by jgyfutub** [comment]
@ArnabChatterjee20k the functionality of tabs is such that if there are 4 tabs then they will change the `isOpen` variable according to their serial number,for eg if 3rd tab is clicked then 'isOpen' will changed to 2 and so on.So, the data of only that tab will be showed whose serial number is equal to `isOpen`.And for other number `<div></div>` will be shown.Taking above example,the data of 3rd tab will be shown because `isOpen==2' as this variable to set to 2  by clicking the 3rd tab due to which 'setIsOpen(2)' occurs.

**Comment by ArnabChatterjee20k** [comment]
Again you are doing the same mistake. 
You are restricting the number of tabs. Dont make specific handlers like this switchTab1 or 2
Make a single handler switchTab which takes an id of the tab and switched to that tab.
For content rendering use react router routes.
The codes is just getting repeated. In future if we are going to some more features here we need to again copy and paste the code. So follow principles of DRY

**Comment by jgyfutub** [comment]
Ok so I just have to make a single SwitchTab function rather than SwitchTab1,2 etc.And render each tab content by react router ?

**Comment by jgyfutub** [comment]
@ArnabChatterjee20k I tried to better the code quality by making files for each tab data and putting serial number in values of each button .Please check the code and tell where shall I improve the code quality.

**Review by ArnabChatterjee20k — CHANGES_REQUESTED** [review]
The boilerplate is getting repeated in both Recent Events and RegisteredEvents
Try to make a single Tab.jsx
You can import this in both of the TabsData and can just put the cards in it.

**Review by ArnabChatterjee20k — CHANGES_REQUESTED** [review]
instead of  
```js
const [isOpen, setIsOpen] = useState(0);
```
make an object in the state with the keys tabLabel,tabData
tabData will contain your components from tabData

**Comment by jgyfutub** [comment]
> The boilerplate is getting repeated in both Recent Events and RegisteredEvents Try to make a single Tab.jsx You can import this in both of the TabsData and can just put the cards in it.

I have just taken these cards as sample I don't know  what type of cards will be shown there

**Comment by jgyfutub** [comment]
@ArnabChatterjee20k I have made an array where all the tabs components are kept,thus calling them by their index number whenever that particular tab is clicked,thereby making the object in the state with the keys tabLabel,tabData.Please review it

**Comment by jgyfutub** [comment]
@ArnabChatterjee20k I have done recent changes suggested in new commits. Thus I sincerely request you to please merge this pr or review it so that I can improve this pr

**Review by ArnabChatterjee20k — CHANGES_REQUESTED** [review]
Thank you for the changes. It can be improved more. 
* Please descriptive name like tabs instead of name like array
* The problem is that you are thinking the situation as binary and trying to solve the whole tab switching in a static manner which can be made dynamic using a proper data structure like objects or maps. 


If we do this thing
```js
const tabs = [ {Tab:RecentEvents, label:"Recent Events"} , {Tab:RegisteredEvents, label:"Registered Events"} ]
const defaultTab = 0
const [tab,setSetTab] = useState(0)

const switchTab(tabIdx)=>setTab(tabIdx)

// rendering the tab labels 
{tabs.map(({label},idx)=><Button onClick={()=>switchTab(idx)}> {label} </Button>)}

// rendering the tabs logic
// current tab will be tabs[tab]
```

**Comment by jgyfutub** [comment]
ok thanks for helping!!

**Comment by ArnabChatterjee20k** [comment]
@jgyfutub any updates?

**Comment by jgyfutub** [comment]
I will make the commits you requested by the end of day

**Comment by jgyfutub** [comment]
@ArnabChatterjee20k I have done the changes as you suggested, please review the recent commit

**Review by ArnabChatterjee20k — APPROVED** [review]
Thanks for creating the requested changes

**Comment by ArnabChatterjee20k** [comment]
Thanks @jgyfutub for your valuable contribution
I am merging it

**Comment by jgyfutub** [comment]
> Thanks @jgyfutub for your valuable contribution
> I am merging it

Thanks for your guidance!

**Pull request merged**
