### PR TITLE
 UI Nav Bar Fix : Allignment , Feature : Hover effect

### PR DESCRIPTION
**Pull request by VarunCypherV**
Wrt to Issue : #13 

Fix : The Nav Bar alignment has been fixed to the content following a margin 
Feature : The Hover with a underline and color change respecting the color palette

### CODE REVIEW

**Comment by ArnabChatterjee20k** [comment]
@VarunCypherV please provide some screenshots or a working video

**Comment by VarunCypherV** [comment]
image
image

**Comment by ArnabChatterjee20k** [comment]
Thanks @VarunCypherV for your contribution. I will be merging it 
But it is having some merge conflicts. Can you please resolve the conflicts?

**Comment by VarunCypherV** [comment]
i have resolved it , please verify !

**Review by ArnabChatterjee20k — APPROVED** [review]

**Pull request merged**
