### PR TITLE
Horizontal scrolling issue fixed

### PR DESCRIPTION
**Pull request by Ayusht777**
Just fix the Horizontal scroll bar issue which is causing by heropage i update this container flex mx-[21px] to container flex px-[21px]

### CODE REVIEW

**Comment by ArnabChatterjee20k** [comment]
Provide the screenshots and follow the issue templates

**Comment by Ayusht777** [comment]
hey did you merge this pull request

**Comment by ArnabChatterjee20k** [comment]
@Ayusht777 thank you for your valuable contribution
I am merging it

**Pull request merged**
